### ISSUE TITLE
Assertions force me to define useless config property

### ISSUE THREAD

**Issue by fabiocarneiro** [spring-cloud/spring-cloud-gcp#1656]
I think the following assertions could be replaced with log warnings because if `spring.datasource.url` is defined, they are not required or used. Ideally, the configuration would not even run, but I am not sure this is possible.

https://github.com/spring-cloud/spring-cloud-gcp/blob/ebd8c3cefa84cf1c19731c6297ad350860aebb37/spring-cloud-gcp-autoconfigure/src/main/java/org/springframework/cloud/gcp/autoconfigure/sql/DefaultCloudSqlJdbcInfoProvider.java#L39-L41

Documented here: https://cloud.spring.io/spring-cloud-static/spring-cloud-gcp/1.1.0.RELEASE/single/spring-cloud-gcp.html#_spring_boot_starter_for_google_cloud_sql

Since I prefer to use URL, as it is a single property to configure everything (or it would be if it was considering `username:password` as it was supposed to), this forces me to define:

```
    cloud:
        gcp:
            sql:
                databaseName: ""
                instanceConnectionName: "_"
```
