### ISSUE TITLE
Is Spring cloud Pub/Sub library automatically reconnects to GCP Pub/Sub API, If GCP Pub/Sub service goes down come back again?

### ISSUE THREAD

**Issue by veereshwaran** [spring-cloud/spring-cloud-gcp#2031]
I am using Spring cloud Pub/Sub library in our micro-services

Our micro-services listening respective Pub/Sub subscriptions. 

After GCP service outage on 11th Nov, our any micro-service not listening topic and message stayed subscriptions and not received in our micro-service.

After restart only, our micro-services start receiving messages from GCP Pub/Sub subscriptions.

I am using default spring-cloud binding configuration and 
```
spring.cloud:
  gcp:
    project-id: ${GCP_PROJECT_ID}
    credentials.location: file:${GCP_CREDENTIALS_LOCATION}
  stream:
    default.contentType: application/json
    bindings:
      my-topic:
        destination: ${TOPIC_NAME}
```

Is there any options to auto-reconnect Pub/Sub this kind of service outage?
