### ISSUE TITLE
spring.cloud.stream.bindings.input.consumer.maxattempts and backOffInitialInterval does not work with pubsub

### ISSUE THREAD

**Issue by thayhoang** [spring-cloud/spring-cloud-gcp#2560]
I used this setting with spring-cloud-starter-stream-rabbit and as I understand behind the scene, Spring create a RetryTemplate and retry the method until maxattempts. This doesn't work with spring-cloud-gcp-pubsub-stream-binder anymore. Here's my configuration

```
spring:
  cloud:
    stream:
      bindings:
        input:
          contentType: application/json
          destination: my-destination
          group: my-group
          consumer:
            concurrency: 6
            maxAttempts: 3
            backOffInitialInterval: 10000
```

Does spring-cloud-gcp-pubsub-stream-binder support maxattempts and backOffInitialInterval?

**Comment by thayhoang** [comment]
I'm looking into org.springframework.cloud.gcp.stream.binder.pubsub,PubSubMessageChannelBinder source code and it looks like it doesn't use any properties under consumer at all. Can anybody help me with this?

```
        @Override
	protected MessageProducer createConsumerEndpoint(ConsumerDestination destination, String group,
			ExtendedConsumerProperties<PubSubConsumerProperties> properties) {

		PubSubInboundChannelAdapter adapter = new PubSubInboundChannelAdapter(this.pubSubTemplate,
				destination.getName());

		ErrorInfrastructure errorInfrastructure = registerErrorInfrastructure(destination, group, properties);
		adapter.setErrorChannel(errorInfrastructure.getErrorChannel());

		return adapter;
	}

```

**Comment by elefeint** [comment]
@thayhoang You are correct; we do not support the additional retry options in the Pub/Sub binder.

Similarly to #2406, are you looking for:
1. Retry if message retrieval from Pub/Sub failed
or
2. Retry if the application message processing logic failed

**Comment by thayhoang** [comment]
Thank you, @elefeint Is the **concurrency** property is respected by pubsub? Because I dont see it referenced in the Pubsub binder class

**Comment by elefeint** [comment]
It is not, but you may find two related Pub/Sub-native properties useful: `spring.cloud.gcp.pubsub.subscriber.parallel-pull-count` and `spring.cloud.gcp.pubsub.subscriber.executor-threads` -- the number of parallel subscribers will be `parallel-pull-count` times `executor-threads`.

**Comment by meltsufin** [comment]
@thayhoang I've just verified that `spring.cloud.stream.bindings.input.consumer.maxAttempts` is in fact used by the Pub/Sub Binder. However, you need to be using it with [message polling](https://docs.spring.io/spring-cloud-gcp/docs/1.2.5.RELEASE/reference/html/#streaming-vs-polled-input).
Note that `PubSubMessageChannelBinder` extends `AbstractMessageChannelBinder`, and that's where there is logic to create a `RetryTemplate` if the `maxAttempts` property is set.
This only applies to failures on message retrieval, however, not application message processing failures.

**Comment by thayhoang** [comment]
> It is not, but you may find two related Pub/Sub-native properties useful: `spring.cloud.gcp.pubsub.subscriber.parallel-pull-count` and `spring.cloud.gcp.pubsub.subscriber.executor-threads` -- the number of parallel subscribers will be `parallel-pull-count` times `executor-threads`.

@elefeint So these 2 settings will be applied for all subscriptions right? What if I want to have a different parallel setting for each subscription. For example I have two subscription, one for main topic, the other for dead letter topic. How can I have different parallel setting for each one

```
spring:
  cloud:
    stream:
      bindings:
        input:
          contentType: application/json
          destination: my-des
          group: test
        input-dlt:
          contentType: application/json
          destination: dead-letter-topic
          group: test
```
